[project]
name = "fastbook2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.5",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
]
